# Metadata
title: MoneyLoop Docs
email: hello@moneyloop.com
logo: "/assets/images/logo_blue.png"
description: >-
  Documentation for MoneyLoop APIs.
github_username: moneyloop-team

# Build settings
remote_theme: pmarsceill/just-the-docs
theme: just-the-docs
